root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build-debug"
  bin = "./tmp/main"
  full_bin = "%USERPROFILE%\go\bin\dlv.exe exec ./tmp/main --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log -- "
  include_ext = ["go"]
  exclude_dir = [".vscode", ".github", "bin", "tmp", "assets", "vendor"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true.
  args_bin = ["server"]
  delay = 1000
  include_dir = []
  exclude_file = []
  kill_delay = "0s"
  follow_symlink = false
  send_interrupt = false
  stop_on_error = true
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
